<?php


defined('ROOTPATH') or define("ROOTPATH", "/var/www/html/lonelymonkeystudio.com/daphne/lolcalculator");
defined('INCLUDE_PATH') or define("INCLUDE_PATH", ROOTPATH.'/includes');
defined('RIOTKEY') or define("RIOTKEY", 'RGAPI-0fe247f8-144b-4c73-a1cf-7d2e4b4b674d');
defined('DB_HOST') or define("DB_HOST", 'lonelymonkey-studio-db.cxxcc958t9rm.us-west-2.rds.amazonaws.com');
defined('DB_USER') or define("DB_USER", 'wayne');
defined('DB_PASS') or define("DB_PASS", 'wyc30709');
defined('DB_NAME') or define("DB_NAME", 'lolcalculator');


?>
