<?php


defined('ROOTPATH') or define("ROOTPATH", "C:/xampp/htdocs/lolcalculator");
defined('INCLUDE_PATH') or define("INCLUDE_PATH", ROOTPATH.'/includes');
defined('RIOTKEY') or define("RIOTKEY", 'RGAPI-0fe247f8-144b-4c73-a1cf-7d2e4b4b674d');
defined('DB_HOST') or define("DB_HOST", 'localhost');
defined('DB_USER') or define("DB_USER", 'root');
defined('DB_PASS') or define("DB_PASS", '');
defined('DB_NAME') or define("DB_NAME", 'lolcalculator');

//error_reporting(0);


?>
